Test changes.

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,51 +1,75 @@
 name: Upload Python Package
 
 on:
-    release:
-        types: [published]
+  release:
+    types: [published]
 
 env:
-    python-version: 3.12
+  PYTHON_VERSION: 3.12
 
 jobs:
-    build:
-        name: Build Package
-        runs-on: ubuntu-latest
-        steps:
-            - uses: actions/checkout@v4
-              with:
-                  fetch-depth: 0
-                  submodules: recursive
-            - name: Install uv and set the python version to ${{ env.python-version }}
-              uses: astral-sh/setup-uv@v5
-              with:
-                  python-version: ${{ env.python-version }}
-            - name: Build package
-              run: uv build
-            - name: Upload dist artifacts
-              uses: actions/upload-artifact@v4
-              with:
-                  name: dist-artifacts
-                  path: dist/
+  build-docker-image:
+    uses: ./.github/workflows/publish_north.yml
+    secrets: inherit
 
-    deploy:
-        name: Upload to PyPI
-        needs: build
-        runs-on: ubuntu-latest
-        environment:
-            name: pypi
-            url: https://pypi.org/p/nomad-north-voila
-        permissions:
-            id-token: write
-        steps:
-            - uses: actions/checkout@v4
-              with:
-                  fetch-depth: 0
-                  submodules: recursive
-            - name: Download dist artifacts
-              uses: actions/download-artifact@v4
-              with:
-                  name: dist-artifacts
-                  path: dist/
-            - name: Publish package distributions to PyPI
-              uses: pypa/gh-action-pypi-publish@release/v1
+  build:
+    name: Build Package
+    runs-on: ubuntu-latest
+    needs: build-docker-image
+    steps:
+      - uses: actions/checkout@v6
+        with:
+          fetch-depth: 0
+      - name: Install uv and set the Python version to ${{ env.PYTHON_VERSION }}
+        uses: astral-sh/setup-uv@v5
+        with:
+          python-version: ${{ env.PYTHON_VERSION }}
+      - name: Overwrite the image tag
+        run: |
+          IMAGE_TAG=$(grep -oP "${{ env.IMAGE }}:\K[^'\",]+" src/nomad_north_voila/north_tools/voila/__init__.py)
+
+          sed -i "s|${{ env.IMAGE }}:${IMAGE_TAG}|${{ env.IMAGE }}:${GITHUB_REF_NAME}|g" \
+          src/nomad_north_voila/north_tools/voila/__init__.py
+
+      - name: build package
+        run: |
+          uv build
+      - name: Check the image tag in the entry point
+        run: |
+          # unzip the built package and check the image tag in the entry point
+          tar -xzf dist/*.tar.gz -C dist/
+          IMAGE_TAG=$(grep -oP "${{ env.IMAGE }}:\K[^'\",]+" dist/nomad_north_voila-*/src/nomad_north_voila/north_tools/voila/__init__.py)
+
+          if [[ "${IMAGE_TAG}" == "${GITHUB_REF_NAME}" ]]; then
+            echo "Before building the Python package, image ${{ env.IMAGE }}:${GITHUB_REF_NAME} is updated for NORTH tool."
+          else
+            echo "Error: Image tag in __init__.py is not correct: ${IMAGE_TAG}. Expected: ${{ env.IMAGE }}:${GITHUB_REF_NAME}"
+            exit 1
+          fi
+
+          # Remove the unzipped package after checking
+          rm -rf dist/nomad_north_voila-*/
+
+      - name: Upload dist artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: dist-artifacts
+          path: dist/
+
+  deploy:
+    name: Upload to PyPI
+    needs: build
+    runs-on: ubuntu-latest
+    environment:
+      name: pypi
+      url: https://pypi.org/p/nomad-north-voila
+    permissions:
+      id-token: write
+    steps:
+      - name: Download dist artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: dist-artifacts
+          path: dist/
+      - name: Publish package distributions to PyPI
+        uses: pypa/gh-action-pypi-publish@release/v1
