Try with workflow run.

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,51 +1,107 @@
 name: Upload Python Package
 
 on:
-    release:
-        types: [published]
+  # workflow_dispatch:
+  workflow_run:
+    workflows: ["publish_north"]
+    types:
+      - completed
 
 env:
-    python-version: 3.12
+  PYTHON_VERSION: 3.12
+  WAIT_TIME: 1800 # 30 minutes in seconds
+  CHECK_INTERVAL: 120 # 2 minutes in seconds
+  IMAGE: "ghcr.io/fairmat-nfdi/nomad-north-voila"
 
 jobs:
-    build:
-        name: Build Package
-        runs-on: ubuntu-latest
-        steps:
-            - uses: actions/checkout@v4
-              with:
-                  fetch-depth: 0
-                  submodules: recursive
-            - name: Install uv and set the python version to ${{ env.python-version }}
-              uses: astral-sh/setup-uv@v5
-              with:
-                  python-version: ${{ env.python-version }}
-            - name: Build package
-              run: uv build
-            - name: Upload dist artifacts
-              uses: actions/upload-artifact@v4
-              with:
-                  name: dist-artifacts
-                  path: dist/
+  # check-if-image-exists:
+  #   name: Check image in GitHub Container Registry
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Check if image exists in GitHub Container Registry
+  #       run: |
+  #         FULL_IMAGE="${{ env.IMAGE }}:${GITHUB_REF_NAME}"
+  #         echo "Checking if image ${FULL_IMAGE} is available..."
+  #         ELAPSED_TIME=0
 
-    deploy:
-        name: Upload to PyPI
-        needs: build
-        runs-on: ubuntu-latest
-        environment:
-            name: pypi
-            url: https://pypi.org/p/nomad-north-voila
-        permissions:
-            id-token: write
-        steps:
-            - uses: actions/checkout@v4
-              with:
-                  fetch-depth: 0
-                  submodules: recursive
-            - name: Download dist artifacts
-              uses: actions/download-artifact@v4
-              with:
-                  name: dist-artifacts
-                  path: dist/
-            - name: Publish package distributions to PyPI
-              uses: pypa/gh-action-pypi-publish@release/v1
+  #         while true; do
+  #           if docker manifest inspect ${FULL_IMAGE} > /dev/null 2>&1; then
+  #             echo "Image ${FULL_IMAGE} found successfully!"
+  #             exit 0
+  #           fi
+
+  #           if [[ ${ELAPSED_TIME} -ge ${{ env.WAIT_TIME }} ]]; then
+  #             echo "Timeout reached (${{ env.WAIT_TIME }} seconds). Image ${FULL_IMAGE} not found!"
+  #             exit 1
+  #           fi
+
+  #           echo "Image not found yet. Retrying in ${{ env.CHECK_INTERVAL }} seconds... (${ELAPSED_TIME}s / ${{ env.WAIT_TIME }}s elapsed)"
+  #           sleep ${{ env.CHECK_INTERVAL }}
+  #           ELAPSED_TIME=$((ELAPSED_TIME + ${{ env.CHECK_INTERVAL }}))
+  #         done
+
+  build:
+    name: Build Package
+    runs-on: ubuntu-latest
+    # needs: check-if-image-exists
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          submodules: recursive
+      - name: Install uv and set the Python version to ${{ env.PYTHON_VERSION }}
+        uses: astral-sh/setup-uv@v5
+        with:
+          python-version: ${{ env.PYTHON_VERSION }}
+
+      - name: Overwrite the image tag
+        run: |
+          IMAGE_TAG=$(grep -oP "${{ env.IMAGE }}:\K[^'\",]+" src/nomad_north_voila/north_tools/voila/__init__.py)
+
+          sed -i "s|${{ env.IMAGE }}:${IMAGE_TAG}|${{ env.IMAGE }}:${GITHUB_REF_NAME}|g" \
+          src/nomad_north_voila/north_tools/voila/__init__.py
+
+      - name: build package
+        run: |
+          # Use SETUPTOOLS_SCM_PRETEND_VERSION to skip the version check due to image_tag modification of the __init__.py file
+          SETUPTOOLS_SCM_PRETEND_VERSION=${GITHUB_REF_NAME#v} uv build
+
+      - name: Check the image tag in the entry point
+        run: |
+          # unzip the built package and check the image tag in the entry point
+          tar -xzf dist/*.tar.gz -C dist/
+          IMAGE_TAG=$(grep -oP "${{ env.IMAGE }}:\K[^'\",]+" dist/nomad_north_voila-*/src/nomad_north_voila/north_tools/voila/__init__.py)
+
+          if [[ "${IMAGE_TAG}" == "${GITHUB_REF_NAME}" ]]; then
+            echo "Before building the Python package, image ${{ env.IMAGE }}:${GITHUB_REF_NAME} is updated for NORTH tool."
+          else
+            echo "Error: Image tag in __init__.py is not correct: ${IMAGE_TAG}. Expected: ${{ env.IMAGE }}:${GITHUB_REF_NAME}"
+            exit 1
+          fi
+
+          # Remove the unzipped package after checking
+          rm -rf dist/nomad_north_voila-*/
+
+      - name: Upload dist artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: dist-artifacts
+          path: dist/
+
+  deploy:
+    name: Upload to PyPI
+    needs: build
+    runs-on: ubuntu-latest
+    environment:
+      name: pypi
+      url: https://pypi.org/p/nomad-north-voila
+    permissions:
+      id-token: write
+    steps:
+      - name: Download dist artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: dist-artifacts
+          path: dist/
+      - name: Publish package distributions to PyPI
+        uses: pypa/gh-action-pypi-publish@release/v1
