Check if test on the build image package works.

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -4,29 +4,92 @@ on:
     release:
         types: [published]
 
-env:
-    python-version: 3.12
+permissions:
+    id-token: write
 
+env:
+    PYTHON-VERSION: 3.12
+    WAIT-TIME: 1800 # 30 minutes in seconds
+    CHECK-INTERVAL: 120 # 2 minutes in seconds
+    IMAGE: "ghcr.io/fairmat-nfdi/nomad-north-voila"
 jobs:
+    check-if-image-exists:
+        name: Check image in GitHub Container Registry
+        runs-on: ubuntu-latest
+        steps:
+            - name: Check if image exists in GitHub Container Registry
+              run: |
+                  FULL_IMAGE="${{ env.IMAGE }}:${GITHUB_REF_NAME}"
+                  echo "Checking for the image ${FULL_IMAGE} to be available..."
+                  ELAPSED_TIME=0
+
+                  while true; do
+                    if docker manifest inspect ${FULL_IMAGE} > /dev/null 2>&1; then
+                      echo "Image ${FULL_IMAGE} found successfully!"
+                      exit 0
+                    fi
+
+                    if [[ ${ELAPSED_TIME} -ge ${{ env.WAIT-TIME }} ]]; then
+                      echo "Timeout reached (${{ env.WAIT-TIME }} seconds). Image ${FULL_IMAGE} not found!"
+                      exit 1
+                    fi
+
+                    echo "Image not found yet. Retrying in ${{ env.CHECK-INTERVAL }} seconds... (${ELAPSED_TIME}s / ${{ env.WAIT-TIME }}s elapsed)"
+                    sleep ${{ env.CHECK-INTERVAL }}
+                    ELAPSED_TIME=$((ELAPSED_TIME + ${{ env.CHECK-INTERVAL }}))
+                  done
+
     build:
         name: Build Package
         runs-on: ubuntu-latest
+        needs: check-if-image-exists
         steps:
             - uses: actions/checkout@v4
               with:
                   fetch-depth: 0
                   submodules: recursive
-            - name: Install uv and set the python version to ${{ env.python-version }}
+            - name: Install uv and set the Python version to ${{ env.PYTHON-VERSION }}
               uses: astral-sh/setup-uv@v5
               with:
-                  python-version: ${{ env.python-version }}
-            - name: Build package
-              run: uv build
+                  python-version: ${{ env.PYTHON-VERSION }}
+
+            - name: Overwrite the image tag
+              run: |
+                  IMAGE_TAG=$(grep -oP "${{ env.IMAGE }}:\K[^'\",]+" src/nomad_north_voila/north_tools/voila/__init__.py)
+
+                  sed -i "s|${{ env.IMAGE }}:${IMAGE_TAG}|${{ env.IMAGE }}:${GITHUB_REF_NAME}|g" \
+                  src/nomad_north_voila/north_tools/voila/__init__.py
+
+            - name: build package
+              run: |
+                  #   IMAGE_TAG=$(grep -oP "${{ env.IMAGE }}:\K[^'\",]+" src/nomad_north_voila/north_tools/voila/__init__.py)
+
+
+                    # Use SETUPTOOLS_SCM_PRETEND_VERSION to skip the version check due to image_tag modification of the __init__.py file
+                    SETUPTOOLS_SCM_PRETEND_VERSION=${GITHUB_REF_NAME#v} uv build
+            - name: Check the image tag in the entry point
+              run: |
+                  # un zip the built package and check the image tag in the entry point
+                  tar -xzf dist/*.tar.gz -C dist/
+                  IMAGE_TAG=$(grep -oP "${{ env.IMAGE }}:\K[^'\",]+" dist/nomad_north_voila-*/nomad_north_voila/north_tools/voila/__init__.py)
+
+                  if [[ "${IMAGE_TAG}" == "${GITHUB_REF_NAME}" ]]; then
+                    echo "Before building the Python package, image ${{ env.IMAGE }}:${GITHUB_REF_NAME} is updated for NORTH tool."
+                  else
+                    echo "Error: Image tag in __init__.py is not correct: ${IMAGE_TAG}. Expected: ${{ env.IMAGE }}:${GITHUB_REF_NAME}"
+                    exit 1
+                  fi
+
+                  # Remove the unzipped package after checking
+                  rm -rf dist/nomad_north_voila-*/
+
             - name: Upload dist artifacts
               uses: actions/upload-artifact@v4
               with:
                   name: dist-artifacts
                   path: dist/
+            - name: Publish package distributions to PyPI
+              uses: pypa/gh-action-pypi-publish@release/v1
 
     deploy:
         name: Upload to PyPI
@@ -38,10 +101,6 @@ jobs:
         permissions:
             id-token: write
         steps:
-            - uses: actions/checkout@v4
-              with:
-                  fetch-depth: 0
-                  submodules: recursive
             - name: Download dist artifacts
               uses: actions/download-artifact@v4
               with:
